### ISSUE TITLE
error on admin - server settings

### ISSUE THREAD

**Issue by bergwiesel** [KL-Psychological-Methodology/ESMira#1]
I get an error message on the server settings page: The server name '' needs to consist of 3 to 30 characters

![errorESMira](https://user-images.githubusercontent.com/2505361/215475664-4e355f8c-7f50-4631-a8f8-3b4ef63771c9.png)

I tried all kind of "server names", consistent with the requirement. What kind of name should there be inserted? I couldn't find anything in the logs.

System: Ubuntu 22.04
Webserver: Apache 2.4.52

**Comment by JodliDev** [comment]
Uhoh! It seems like error message has not been fitted to multiple languages.

I assume that you have set a server name for German but non for Swedish (which is why the server refuses to save).
If you change the language to Swedish at the right top and then add a server name, it should work.
I will address that issue in the next update (Ill probably remove the server name requirement all-together)
