### ISSUE TITLE
App no longer starting

### ISSUE THREAD

**Issue by gsalzer** [KL-Psychological-Methodology/ESMira#27]
We are currently running a long-term study, where users have to answer daily a question. Since a few days, some of the users report that the Esmira app stopped working. Rebooting the phone and reinstalling the app don't help. There is no reliable pattern yet. So far, only Android users are concerned, no reports from iOS people. Maybe there is a connection to the update of the Esmira app on Nov 19? However, there are Android users with the newest version of the app using it without problems.

Any suggestions what to do?

**Comment by SelinaDev** [comment]
Thank you for notifying us of this issue.
It seems this problem was indeed caused by the recent update, and I apologize that it interfered with your study.
I tracked it down to a database update that runs on startup. I used a DROP COLUMN sql command. Unfortunately I was unaware that this command was only introduced relatively recently. Due to this the update works on newer devices, including all of the devices we tested the update on prior to release. However, on devices running an older version this causes a syntax error in sql during startup, which then crashes the application.
I was indeed able to reproduce this problem on one of my older android devices, and have already created an update that fixes this issue on that device. I have uploaded this version (2.15.1) already, and it should hopefully be approved and become avalable in the App Store later today.

**Comment by gsalzer** [comment]
The first users have updated the app, and it seems to work again. Thanks a lot for your help! I will not be shy and let you know if there is any problem remaining ;-). Closing for now ...

**Comment by gsalzer** [comment]
One user running Android 11 (see image for system info) reports that the app still doesn't start but gives a message saying that the app has been terminated multiple times ("Als anzeige kommt bei mir die app wurde mehrfach beendet").

![image](https://github.com/user-attachments/assets/d0f3de07-b244-4161-8401-97730d4242fd)

**Comment by gsalzer** [comment]
@SelinaDev Do you have any clue regarding what may be going wrong? Or is Android 11 just too old?

**Comment by SelinaDev** [comment]
> @SelinaDev Do you have any clue regarding what may be going wrong? Or is Android 11 just too old?

Android 11 being too old should not be the problem, as I tested in on a device running Android 10.
I would ask you to confirm the participant has actually updated to 2.15.1, as Jodli suggested. After that I can look into it, but I'm afraid in this case I do not have that much information.

**Comment by gsalzer** [comment]
The study participant now not only reinstalled the app (which was not sufficient), but also run an explicit update, and this finally made it. At the moment, all study participants seem happy. Let's hope it stays that way ;-)
Thanks for your support!
